#cloud-config

packages:
  - git

runcmd:
  - dist=/home/azureuser/iot-edge-1.2-tpm
  - patchdir=ibm-vtpm-patches
  - mkdir ${dist}
  - cd ${dist}
  # Download scripts. TODO: later replace with git clone
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/0-1-fix-ubuntu-18.04.sh -O 0-1-fix-ubuntu-18.04.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/1-1-download-libs.sh -O 1-1-download-libs.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/1-2-build-tpm2-tss.sh -O 1-2-build-tpm2-tss.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/1-3-build-tpm2-abmrd.sh -O 1-3-build-tpm2-abmrd.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/1-4-build-tpm2-tools.sh -O 1-4-build-tpm2-tools.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/1-5-build-tpm2-pkcs11.sh -O 1-5-build-tpm2-pkcs11.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/2-install-vtpm.sh -O 2-install-vtpm.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/3-install-pkcs11-tool.sh -O 3-install-pkcs11-tool.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/4-install-edge-x86.sh -O 4-install-edge-x86.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/5-pkcs11-init.sh -O 5-pkcs11-init.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/iot-edge-config-azure.sh -O iot-edge-config-azure.sh
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/config.toml.est.template -O config.toml.est.template
  - mkdir ${patchdir}
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/makefile.patch -O ${patchdir}/makefile.patch
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/ibmswtpm2-NVDynamic-Fix-use-of-uninitialized-value.patch -O ${patchdir}/ibmswtpm2-NVDynamic-Fix-use-of-uninitialized-value.patch
  - wget https://vislepakazurecli.blob.core.windows.net/tpmscripts/ibmswtpm2-TcpServerPosix-Fix-use-of-uninitialized-value.patch -O ${patchdir}/ibmswtpm2-TcpServerPosix-Fix-use-of-uninitialized-value.patch
  # Make scripts executable
  - chmod +x *.sh
  # Make sure we don't have any Windows line ednings
  - sed -i.bak 's/\r$//g' *.sh
  # Install TPM tools, vTPM and IoT Edge
  - ./0-1-fix-ubuntu-18.04.sh
  - ./1-1-download-libs.sh
  - ./1-2-build-tpm2-tss.sh
  - ./1-3-build-tpm2-abmrd.sh
  - ./1-4-build-tpm2-tools.sh
  - ./1-5-build-tpm2-pkcs11.sh
  - ./2-install-vtpm.sh
  - ./3-install-pkcs11-tool.sh
  - ./4-install-edge-x86.sh
  - ./5-pkcs11-init.sh

final_message: "The system is finally up, after $UPTIME seconds"