#cloud-config

packages:
  - git

runcmd:
  - cd /home/azureuser
  # Clone the repo
  - git clone https://github.com/arlotito/iot-edge-1.2-tpm.git
  - cd iot-edge-1.2-tpm/scripts
  # Make scripts executable
  - chmod +x *.sh
  # Make sure we don't have any Windows line ednings
  - sed -i.bak 's/\r$//g' *.sh
  # Install TPM tools, vTPM and IoT Edge
  - ./0-1-fix-ubuntu-18.04.sh
  - ./1-1-download-libs.sh
  - ./1-2-build-tpm2-tss.sh
  - ./1-3-build-tpm2-abmrd.sh
  - ./1-4-build-tpm2-tools.sh
  - ./1-5-build-tpm2-pkcs11.sh
  - ./2-install-vtpm.sh
  - ./3-install-pkcs11-tool.sh
  - ./4-install-edge-x86.sh
  - ./5-pkcs11-init.sh

final_message: "The system is finally up, after $UPTIME seconds"